version: '3'
services:
  frontend:
    build: ./FrontEnd
    # image: vueapp:0.0.1
    container_name: "vue_app_container"
    ports:
      - "8080:8080"
    networks:
      - app-network
  backend:
    build: ./BackEndApi
    container_name: "backend_app_container"
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    external: true