version: '3'
services:
  vue:
    build: ./vue_app
    # image: vueapp:0.0.1
    container_name: "vue_app_container"
    ports:
      - "8080:8080"
    networks:
      - db_postgres
  backend:
    build: ./BackEndApi
    container_name: "backend_app_container"
    ports:
      - "3000:3000"
    networks:
      - db_postgres
networks:
  db_postgres:
    external: true